---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lldap-db-pass
  namespace: lldap
spec:
  encryptedData:
    password: AgBDw/x378ic6YGYEVVZMVBGertTgabz3ORpoCDuNZZROKtEs2/0BBr4yu8srh25VSSvckZBDF/cTec/2A121bTziPythHjvlRsCy7g/cXnJIHmPcU6mqiA/7EpFehAJ9BvonFsmkW62Pj761uupYTSftj2PASzDrDZY9IO5BkRPHmZsUQYoNLX4SkxLVuqColQH4CfrHmNHVNuk8reVcvurpKvBJ6x2wWAae89IUYTduP2bcdpxf1LHj8wgBrEHfN4frqZcxjKh1uPMggViPkeBqjQ5JgzY2d9t7N8taPHuUvscN0oFFwm2M81t0Q4n9BbjH5apRKGXGdHGVR5f9FWnIDrkVAO8NW52Ko51CzAC95AoQRDMPVYjSpKZ4VLdh0tZJixTGejHTK64Jf3tehw7aL/hv07S4X7/sx9jATSDIwcMy4wyRCYRxa0w2nZCR+L9PkpIBr4t+kuFZe/uT804J7fRqu420GFA2FTs9puAfuVulFLi6g6q7gm6LQniDR6N8omkoP4tj7H/wd5MJwF1nGDib7SbDG0o9fw8sqnCa9Rul4NPjFBmGEydO9aI9UJ8CH6XwID8Pf5BnewOsBZ1kHbR9mOfUF1R570rhzmEzMF0trZk81H5N0ZrSILSBvym4auJNeZnYLEGUuYxhQJzFsKi+jF2O1MlqDrV4oegSkyKfwsB61K/8HVgaIYMtzV8Cf/vWzfsegaI/j3626Bw1BY=
  template:
    metadata:
      creationTimestamp: null
      name: lldap-db-pass
      namespace: lldap
