---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lldap-secret
  namespace: lldap
spec:
  encryptedData:
    LLDAP_JWT_SECRET: AgA4z8GbAFjqn2JBQR0Bd+aAXiz0cb6OYsUbHb5i0DhgYUSHFro0F7WEQcNE686IlhRzEpIX9SE+X8gf7MKI7t2PqkkZeTRsGqpZgPYr/Zoda9WE+2yoTnspXl7McT0ZmgrEd9B4/M4yM0aNY83T8ZmuXNU7F/GLUsIM6JGdyjNMaRGzytt2kDNIJZ9Nh2QR12474FUgJo+9pA9Qu95n2r0lW6dB+IbO1sFEln94qcUD3UVp8dRO7zSdRqSw9leQK2Bfqcb1qFjqqjYuV0+orhbLjD2RvlLY7w8u83aP9Ty5XENUYsB57TWAo6cld5tkNk7HKAmvgI+WS3VHm0QFrDKAqkrSrSWRAXH31R35NP17HCRFg/NPSYSZs3dPPdVfU4O0M9FAfp4RKKEfrGxNXI9/rgMWpl305sRqOpTgG50zCo9K6/usGyTVdcFl+NSBPbTpZnRImdunVf9fkBjpPue1fhPs06qIR3ldcpk3r5g4qbUjs7tSG6YNYJvXuNv9oCCJpOYyNkquR3UxDqhMLZPsHvmaCS7ivpHW9mosQnHRs55Axe+LtauIa5nEf9Mp8D8j8vjaXntbGSCrnJC9+NMNWe0eX6zYLpppwiqukWX4NH2ybnL5wxBPl0rroDkAxIqXqAOqhzi6mhL1ifjU+9W5p45KKc+l9bTSmn1noZgpkj0er202eqmeRtLmi2N7+WetXYm9emICvLccBl4FWcV1JZlUprdJAaWSyMJKGntIrF0KVhv1ASDiam/WyA==
    LLDAP_LDAP_USER_PASS: AgBPXiR6sJvQVEYFbWYnxXl0BS1X/O3cNTP0uvolxcgtGZamwI7FJ2RlRHXr76DSokMNRzjXT82C8crZoyVpl1g2Ze4tyOYa6PrxIlILozoFNs5X1UFPOaIZB5n0ysF6kFSnF4c6UugqaFjjyjllEqCAPIfwXEyHO1qbRuAqNgTtqc7Hl55UiCAbu1v52zxgAgGI9jEDv18BELNBBtLSRIIqWilGqgoWhD9fs4LEHX7BhoA2QOSH7KYbejrhiOb3ueXZ3ki14FUf3wMv3UcZoI5yKis7wxGuqsYTCbto9hLkcooPjstKjHI6Vy4CVF2axZj1ILjlQLVki7/k7xO7h++5mlhwFc6Qu55eAAr73NgD1eTZY7T4JHWRWiG6c4lx6HcP+aCf+fRB6ZJdL2inaeRcDp0szUm+nYyDlV89ixQCx4mqQhhWOlDXI5KS66NyoNg5+foO3gQKEuxuBePLg1um+l66iGgWTGaMu7BP+A2RjgSAZqTwEDliDK4qIlxQ5FGycmRjZHlo+jJTXyQDqbTZZp6hpQPHRNHkb9Ltbxv9Kj7s0sXHFU5nq/GEeBd7QCE9fvClm0TUI7Dwf7TDEr4AjNrYkpD5ARjw+6WrYIjU1du1nqY9i5mpNxSd1O1sgktAoPqxUI1p2x9ovTgnkzUnceu/RLU+1EahkJIYDs7T363QI3uSNxUd/RFASgo/7uluZmzgcqxK1nEKczIX37+OSA==
  template:
    metadata:
      creationTimestamp: null
      name: lldap-secret
      namespace: lldap
