---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC1ez0bjCpu47xtqQP96ololGzM4l6RIfKH3Es4DbnZzM3zoQILCretR9uYFch/LzVal1xkMeumMYMtEHdLUajUX5hK6UZg7pdOF2/hvVLVzB0E191Betl16/mXe2TMSzZD7A3oLlyyxm41WWVue0/YlBknZjCeTruVdKg1gP59BtDjxqr1pYrlxAb+8WpfuqF0uo/19GWXV+euZ9OXC7WGHB45zA29TTSf/5pKZ92z8hBSNpFfNF0ddbExMB0AnFBF4bquLz/wFigx2XR9MW6L/ZW086JonpkbmhPnCT5ZHA4/Wwl0Do5GpiGabN2MEvYM+vHmPipDL+k5PqlFtK9OS1tEwaLhe77E2c184mJj5ZGeozpKW2jARg+j5ilY2xT1MV1K+KdTNMeLEQtDQHeacZyrhRNMGU3WjC/2JVkVfeIIp7ekVLDly2KhEPUzcOMNA9XDmjETihrJgss7AAJhfz8DRo+CHCUG4Vjqoh//y0xtq6zrjXVNtV0KpuDiDEMMcs6cmBjPisQLGO+MJS/VjjsSc82Z6HIiZtWtQneiLWCWrWqILEZabmmrsNlYU0r4H1HlhMBDqLpi7oiISXB8VzpdvXnrYdaB9NS+XUw3XKBjx64GnMpK+krLI+LbS6TwAcRcEUt0LYdJ9kKe0/Ts0WLAW2pwGPRTIfe9oDx3lXJtl3cp15ggt1DMlwW+a+TcSbWF7CbKXbHpY2qpH0ZiCw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
