---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_ADMIN_PASSWORD: AgAoSY3lu9Bq9zGlsuYEdqk4GhC1/Zji59KvBmOAngc2sRcuJRi9389S/EfsWOi8VkcLrxd5qM+e6UERebIp1668ch0ircTC/3ZKdsHcRK1tVrwkLnZfjFm7RsBDp2cjJKs+4wi2q+eS0PoURFjLuTXHRHiYJ/Q1BIfParEE57895nB+6Iq2llOC/frDkg5l6AXAlXM9+k7pdjtvJ9tt5XyZBXl4RvT3IQYz+WBYUz9gtxy3EERH3u25HaSwEyBZatU1/hNLqySWmhYyyprXjgyW08vUSGthOObgiXU7IrVCBf2OKavzmAPFw3Kg8ru2eTVhX5QnZg/sQdLFaHkykcH+gWyHInDyCV/sj/RZhz3Xpui0loDWiH7Tu73EZUWlD8lRgjVV0MOEUVWDYtm8pryuFT4UN73rmaZopRGZizdx5x59GG9NVFot19Je0v1nu6+8gXzLms82hLwAqxtNHOEMOKHcyfNX8k7bEEtSdJwYMtqwa0waV/XD+FPNszpOT9BHJFWkWNJR/sdONn4IFzUnmg+6hgFjy4sTbyOvn/5OSFrwFV0qCvcWKyY40TMV2EPPV4cpwpW25pdthODJCoc6HfUYnnnV7a0GYTHigvDH0Hh0y/4y6pPV7dYvKa8k9YHG642/gdDlGDTVzWpfAfuqLPVUhfIg3SLWIloj09sNW4GRwYbfwvyU5kQOrThTfDmfGXkclHxNoZyYrRl+rBxTwA==
    NEXTCLOUD_ADMIN_USER: AgA8BrhqpYHmGl/MAqDuK+HUFQps/HEqj72U18NFRLonRh1fJjgIImBEy1Dq4HlU6fzbOFPizelhVRS7xWXiqkM4Vv2dcH9O+6+94PVfqYWT3o6hp6ZLwhBUosJ/rLy3qMpfj6Ygg6uLrMg9/mIC6YYfkvR1gNmjcywPcdI7cM5RLIsxHuaOUb4+svD9zJ4BW79yHSEf95jn2hNIDFZDJYtG/wRExln83wcalJbCdOUZLZgp77LkGDz1GRp5JdzFEAlrfo/5LPOGf+s9gsGcXQDyi1jlwjo7s2ZRY34YrWvp5ick3dIcluXoI1v48MC4YLANiTJkVVKoMu54T5iHGM4II/V+KW+K30DVcV8YlFvprbuvATgSUhmJA7ahfGNlPYkJKStV/eEHm2kgYsYKhB7QxjEECsSsIlSb36McQ/IaFlCvX4ucInyWXRMGJgf4Mtkgce/DrIoMxbwXYj7T3oRiGjPx+ImC4gFcocNMFLoEVYUDKIjgADolPneUgCXOKxrzkuTwjUG1MH7bSdcIjzQShfttKp5RsnVH3Jab9UGhH2avq82FzbpgpAIXDZO/mlkED5l3UX6e4ltCwtyFa39lF3H6ioJfUzKkoT2J/b17B6fdsgimS/o225L1LnJsGu/OFp4jwqXcbqYHqBN19f4E1ZWujNboWCk7qaI4qnFuorNo8aVl4FGfKCFMsYQy/BH7bG5C0Q==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
