---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-db-pass
  namespace: nextcloud
spec:
  encryptedData:
    password: AgAhsyiBpVU0+Tgr9bmT6ZghD2L2qCkaSEonmuhPldTwhzKXwHJptkpgOkrU4BPrtzne46Pb4UU9PNWdTpsw3xJ96kB1yOU4BcMj500EVsDqVqBfZiR4TwkhJup6gh3yzDdb+NYWY1l36ujlaypdSlJMu6WtK8uQrR8RSiaKBOHxGjUDsN24c7+lnxvtVPkYgvzHvcR2pC4VzAnFcDw0FNQQFO9wcfdCkIO5qHuV+YvUJhWJ2UyqZWK1A0aa1Jp23XO/lhi8j9X1VXPbzDtp5Tv7Aiah0OvByZz0VBDG+CCIitGnJmhFRrpQnx97b5Bi2DacaUtbXuFqGL3dX18hFlx64uL9ojPUprte3lJdtX7rP1mZtcAtDluIUwESrE6rS3NITygcii5NTsJ2t3+9SgQjNILO85fFlS2Se9Q4GrANxiWgcCDWa8EWL00YPH/VFwjLJiXL9Y99T/+mmlgKOkA2HaJemHxsqet4Brj5t/1RFBLypQ7Zpa7UB/C9FHFGdlPabXUWf7Kkf8P5sHkA3A7VwZFzse3Q2lJSnhoqzufy99MWQM+LzhxCCYwCuIdbOBTGqz2t/oa4rWHHUIQkcrSl1RK6JHTfyvCW5/HAl9uyK5nHMCjDof0UAArVhTnr3N4GY4bO0wl6Z7PFvka4KO7Qu7g6KjIxB/+C9t7rH9F21cItcw/mTOZbLBPGdRbQbdeYX/rE6kurOPb5uAMMmlA=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-db-pass
      namespace: nextcloud
