---
# manifests/04-metallb/metallb-pool.yaml
# Ejecutar DESPUÉS de que los pods de MetalLB estén Ready
# Rango: 192.168.1.80-90 (libre en la red del laboratorio)
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ecocloud-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.80-192.168.1.90
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ecocloud-l2-adv
  namespace: metallb-system
