---
# manifests/06-adguard/adguard.yaml
# Labels añadidos en metadata del Service (incidencia TFG sección 7.2.2)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: default
  labels:
    app: adguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - name: adguard
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 3000
            - containerPort: 80
          volumeMounts:
            - name: work
              mountPath: /opt/adguardhome/work
            - name: conf
              mountPath: /opt/adguardhome/conf
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: adguard-work
        - name: conf
          persistentVolumeClaim:
            claimName: adguard-conf
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-svc
  namespace: adguard
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.80
spec:
  selector:
    app: adguard
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
    - protocol: TCP
      port: 53
      targetPort: 53
    - protocol: TCP
      port: 80
      targetPort: 3000
